services:
  frontend:
    build:
      target: production
    ports: []

  backend:
    build:
      target: production

  dbbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_EXTRA_OPTS=-Z1 --blobs
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    networks:
      - internal

volumes:
  pgbackups:
