"""add job listings

Revision ID: 4fdc0869f390
Revises: 627a4474e6fa
Create Date: 2026-03-23 23:01:53.599313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdc0869f390'
down_revision: Union[str, Sequence[str], None] = '627a4474e6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('locations', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_listing_studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_listing_id', sa.Integer(), nullable=False),
    sa.Column('study', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_listing_studies_job_listing_id'), 'job_listing_studies', ['job_listing_id'], unique=False)
    op.create_table('job_listing_years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_listing_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_listing_years_job_listing_id'), 'job_listing_years', ['job_listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_listing_years_job_listing_id'), table_name='job_listing_years')
    op.drop_table('job_listing_years')
    op.drop_index(op.f('ix_job_listing_studies_job_listing_id'), table_name='job_listing_studies')
    op.drop_table('job_listing_studies')
    op.drop_table('job_listings')
    # ### end Alembic commands ###
