name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/mgr/services/betauia.net

            git config --global user.email "ci@githubactions.com"
            git config --global user.name "GitHub Actions"
            git pull origin master || { echo "Git pull failed"; exit 1; }

            docker compose -f compose.yaml -f compose.prod.yaml build || { echo "Docker compose build failed"; exit 1; }
            docker compose -f compose.yaml -f compose.prod.yaml up -d || { echo "Docker compose up failed"; exit 1; }
