FROM node:20-alpine AS builder

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./

COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.13-alpine AS final

WORKDIR /app

COPY --from=builder /app/dist /app


